sudo: required
services:
  - docker

before_install:
  - docker build -t mattmoran25/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mattmoran25/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-west-2-773327279533"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
    
